"""Persisted pipeline state public API."""

from __future__ import annotations

from trans_novel.pipeline.state.access import runstore_for
from trans_novel.pipeline.state.checkpoint import begin_polish, begin_translate, clear
from trans_novel.pipeline.state.clone import clone_closed_runstore
from trans_novel.pipeline.state.context import RollingContext
from trans_novel.pipeline.state.models import (
    BEST_EFFORT_NODES,
    NODE_ANALYZE,
    NODE_ASSEMBLE,
    NODE_DETERMINISTIC_QA,
    NODE_FAILED_PERMANENT,
    NODE_FAILED_RETRYABLE,
    NODE_LAYOUT,
    NODE_MINE_TERMS,
    NODE_NAME_TERMS,
    NODE_PENDING,
    NODE_POLISH,
    NODE_PREPARE,
    NODE_REPAIR,
    NODE_REPORT,
    NODE_RUNNING,
    NODE_SKIPPED,
    NODE_SUCCEEDED,
    NODE_TITLES,
    NODE_TRANSLATE,
    RUN_INPUT_SCHEMA_VERSION,
    RUN_STATE_SCHEMA_VERSION,
    SCOPE_BOOK,
    SCOPE_CHAPTER,
    STATUS_DONE,
    STATUS_PENDING,
    AnalysisFlags,
    ChapterIndex,
    ChapterProgress,
    ChapterStatus,
    IdentityMismatchError,
    NodeFailure,
    NodeState,
    NodeStatus,
    PolishBatch,
    RepairIssue,
    RunIdentity,
    RunState,
    chapter_node_key,
    input_fingerprint,
    now_iso,
    source_bytes_hash,
    stable_digest,
)
from trans_novel.pipeline.state.note_migration import (
    commit_note_migration,
    recover_note_migration,
)
from trans_novel.pipeline.state.output_selection import (
    SavedOutputSelection,
    load_output_selection,
    save_output_selection,
)
from trans_novel.pipeline.state.store import RunStore, slugify
from trans_novel.postprocess.language import normalize_lang_code

__all__ = [
    "BEST_EFFORT_NODES",
    "NODE_ANALYZE",
    "NODE_ASSEMBLE",
    "NODE_DETERMINISTIC_QA",
    "NODE_FAILED_PERMANENT",
    "NODE_FAILED_RETRYABLE",
    "NODE_LAYOUT",
    "NODE_MINE_TERMS",
    "NODE_NAME_TERMS",
    "NODE_PENDING",
    "NODE_POLISH",
    "NODE_PREPARE",
    "NODE_REPAIR",
    "NODE_REPORT",
    "NODE_RUNNING",
    "NODE_SKIPPED",
    "NODE_SUCCEEDED",
    "NODE_TITLES",
    "NODE_TRANSLATE",
    "RUN_INPUT_SCHEMA_VERSION",
    "RUN_STATE_SCHEMA_VERSION",
    "SCOPE_BOOK",
    "SCOPE_CHAPTER",
    "STATUS_DONE",
    "STATUS_PENDING",
    "AnalysisFlags",
    "ChapterIndex",
    "ChapterProgress",
    "ChapterStatus",
    "IdentityMismatchError",
    "NodeFailure",
    "NodeState",
    "NodeStatus",
    "PolishBatch",
    "RepairIssue",
    "RollingContext",
    "RunIdentity",
    "RunState",
    "RunStore",
    "SavedOutputSelection",
    "begin_polish",
    "begin_translate",
    "chapter_node_key",
    "clear",
    "clone_closed_runstore",
    "commit_note_migration",
    "input_fingerprint",
    "load_output_selection",
    "normalize_lang_code",
    "now_iso",
    "recover_note_migration",
    "runstore_for",
    "save_output_selection",
    "slugify",
    "source_bytes_hash",
    "stable_digest",
]
